exclude: [README.md, .gitignore]
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
encoding: utf-8
github: [metadata]
repository: itruett/sunnskyeslabradors.com
theme: minima
sass:
    style: compressed
